services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2022
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Zzdigimon@315"
    ports:
      - "1433:1433"
    volumes:
      - docker_sqlserver_data:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Zzdigimon@315" -Q "SELECT 1" -C
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - funews-network

  api:
    build:
      context: ..
      dockerfile: HuynhHuuToan_ SE1856_A01_BE/Dockerfile
    container_name: funews-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FUNewsManagementSystem;User Id=sa;Password=Zzdigimon@315;TrustServerCertificate=True;Encrypt=True;
    expose:
      - "8080"
    ports:
      - "5024:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - funews-network
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`toanhhqe180078prn232.14.225.231.92.sslip.io`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.docker.network=coolify"

volumes:
  docker_sqlserver_data:

networks:
  funews-network:
    driver: bridge
  
  coolify:
    external: true
    name: coolify
