<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>HuynhHuuToan__SE1856_A01_Service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HuynhHuuToan_ SE1856_A01_Repository\HuynhHuuToan_ SE1856_A01_Repository.csproj" />
  </ItemGroup>

</Project>
